# The following variables should be set in the pipeline:
# - AZURE_SERVICE_CONNECTION
# - AZURE_DEVOPS_AGENT_POOL
# - APIM_PUBLISHER_EMAIL
# - customDomain
# - gatewayCustomDomainHostname
# - portalCustomDomainHostname
# - managementCustomDomainHostname
# - gatewayCustomDomainCertificate
# - portalCustomDomainCertificate
# - managementCustomDomainCertificate
# - trustedRootCertificate

trigger: none
pr: none
resources:
  pipelines:
    - pipeline: apimAppGatewayCI
      source: 'APIM + App Gateway Recipe CI'
      trigger: 
        branches:
          include:
          - main

name: 'APIM + App Gateway Recipe CD - Terraform'

pool: 
  vmImage: 'ubuntu-latest'

stages:
  - stage: Deploy
    displayName: Deploy
    
    jobs:
      - job: DeployTerraform
        timeoutInMinutes: 360
        displayName: Deploy Terraform Files
        variables:
        - template: variables/apim-appgw-recipe-terraform.yml

        steps:
          - template: ./templates/terraform-deploy.yml
            parameters:
              terraformPath: ./src/az-webapp-apim-appgw/deploy/terraform
              terraformVariables: '-var "resource_group_name=$(resourceGroupName)" -var "dns_zone_resource_group_name=$(operationsResourceGroupName)" -var "newOrExistingDnsZones=$(newOrExistingDnsZones)" -var "resourceBaseName=$(resourceBaseName)" -var "vnet_address_prefix=$(vnetAddressPrefix)" -var "vnet_subnet_app_service_integration_address_prefixes=$(vnetSubnetAppServiceIntegrationAddressPrefix)" -var "vnet_subnet_private_endpoints_address_prefixes=$(vnetSubnetPrivateEndpointAddressPrefix)" -var "vnet_subnet_apim_adddress_prefixes=$(vnetSubnetApimAdddressPrefixes)" -var "vnet_subnet_appgw_adddress_prefixes=$(vnetSubnetAppGwAdddressPrefixes)" -var "azurerm_api_management_publisher_name=$(apimPublisherName)" -var "azurerm_api_management_publisher_email=$(APIM_PUBLISHER_EMAIL)" -var "custom_domain=$(CUSTOMDOMAIN)" -var "gateway_custom_domain_hostname=$(GATEWAYCUSTOMDOMAINHOSTNAME)" -var "portal_custom_domain_hostname=$(PORTALCUSTOMDOMAINHOSTNAME)" -var "management_custom_domain_hostname=$(MANAGEMENTCUSTOMDOMAINHOSTNAME)" -var "gateway_custom_domain_certificate=$(GATEWAYCUSTOMDOMAINCERTIFICATE)" -var "portal_custom_domain_certificate=$(PORTALCUSTOMDOMAINCERTIFICATE)" -var "management_custom_domain_certificate=$(MANAGEMENTCUSTOMDOMAINCERTIFICATE)" -var "trusted_root_certificate=$(TRUSTEDROOTCERTIFICATE)" -var "location=$(location)" -var "tags=$(tags)"'
              serviceConnection: $(AZURE_SERVICE_CONNECTION)
              tfStateResourceGroupName: $(tfStateResourceGroupName)
              tfStateStorageAccountName: $(tfStateStorageAccountName)
              tfStateContainerName: $(tfStateContainerName)
              tfStateFileName: '$(tfStateFileName)'

          - template: ./templates/vnet-peering.yml
            parameters:
              azureSubscription: $(AZURE_SERVICE_CONNECTION)
              sourceResourceGroupName: $(resourceGroupName)
              targetResourceGroupName: $(operationsResourceGroupName)
              targetVirtualNetworkName: $(operationsVirtualNetworkName)
              infraSourceType: terraform

          - task: Bash@3
            displayName: "Pull Azure Web App Name From Outputs"
            name: retrieveTerraformOutputVariables
            inputs:
              targetType: 'inline'
              workingDirectory: "$(Pipeline.Workspace)/terraform"
              script: |
                webAppName=$(jq -r '.web_app_name.value' outputs.json)
                echo "Web App name: $webAppName"
                echo "##vso[task.setvariable variable=azureWebAppName;isOutput=true]$webAppName"

                webAppPlanName=$(jq -r '.web_app_plan_name.value' outputs.json)
                echo "Web App plan name: $webAppPlanName"
                echo "##vso[task.setvariable variable=azureWebAppPlanName;]$webAppPlanName"

          - task: AzureCLI@2
            displayName: Change App Service Plan SKU
            inputs:
              azureSubscription: $(AZURE_SERVICE_CONNECTION)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az appservice plan update \
                  --resource-group '$(resourceGroupName)' \
                  --name '$(azureWebAppPlanName)' \
                  --sku 'B1'

      - job: DeployAzureWebApp
        dependsOn: DeployTerraform
        displayName: Deploy Azure Web App
        pool:
          name: $(AZURE_DEVOPS_AGENT_POOL)
        variables:
        - template: variables/apim-appgw-recipe-terraform.yml
        - name: azureWebAppName
          value: $[ dependencies.DeployTerraform.outputs['retrieveTerraformOutputVariables.azureWebAppName'] ]

        steps:
          - template: ./templates/dotnet-build.yml
            parameters: 
              sourceCodePath: '**/src/common/app_code/WeatherForecastAPI/*.csproj'
              testCodePath: ''
              buildConfiguration: 'Release'
              codeCoverageThreshold: '$(codeCoverageThreshold)'

          - task: DownloadPipelineArtifact@2
            displayName: "Download Web App Artifact"
            inputs:
              buildType: "current"
              artifact: "dotnetArtifact"
              targetPath: "$(Pipeline.Workspace)/dotnetArtifact"

          - task: DownloadPipelineArtifact@2
            displayName: "Download Terraform Artifact"
            inputs:
              buildType: "current"
              artifact: "terraform"
              targetPath: "$(Pipeline.Workspace)/terraform"

          - task: AzureRMWebAppDeployment@4
            displayName: Deploy Web App
            inputs:
              WebAppName: '$(azureWebAppName)'
              ResourceGroupName: '$(resourceGroupName)'
              azureSubscription: $(AZURE_SERVICE_CONNECTION)
              Package: '$(Pipeline.Workspace)/dotnetArtifact/WeatherForecastAPI.zip'