trigger:
  branches:
    include:
      - '*'

pool:
  vmImage: "windows-2019"

jobs:
  - job: SecureCodeAnalysis
    displayName: 'Guardian Security and Compliance Analysis'
    steps:
      - task: CredScan@2
        displayName: Run CredScan V2
        inputs:
          toolMajorVersion: 'V2'
          batchSize: '20'

      - task: SdtReport@2
        displayName: 'Create Security Analysis Report'
        inputs:
          GdnExportTsvFile: true
          GdnExportHtmlFile: true
          GdnExportOutputBaselineFile: myBaseline
          GdnExportOutputBaseline: myBaselinedResults
          GdnExportOutputSuppressionFile: mySuppressions
          GdnExportOutputSuppressionSet: mySuppressionSet
          GdnExportPolicyMinSev: Warning
          GdnExportGdnToolApiScanSeverity: Warning
          GdnExportGdnToolArmorySeverity: Warning
          GdnExportGdnToolBanditSeverity: Warning
          GdnExportGdnToolBinSkimSeverity: Warning
          GdnExportGdnToolCodesignValidationSeverity: Warning
          GdnExportGdnToolCredScanSeverity: Warning
          GdnExportGdnToolESLintSeverity: Warning
          GdnExportGdnToolFlawfinderSeverity: Warning
          GdnExportGdnToolFortifyScaSeverity: Warning
          GdnExportGdnToolFxCopSeverity: Warning
          GdnExportGdnToolGosecSeverity: Warning
          GdnExportGdnToolModernCopSeverity: Warning
          GdnExportGdnToolPoliCheckSeverity: Warning
          GdnExportGdnToolRoslynAnalyzersSeverity: Warning
          GdnExportGdnToolSDLNativeRulesSeverity: Warning
          GdnExportGdnToolSemmleSeverity: Warning
          GdnExportGdnToolSpotBugsSeverity: Warning
          GdnExportGdnToolTSLintSeverity: Warning
        continueOnError: true
        condition: succeededOrFailed()

      - task: PublishSecurityAnalysisLogs@3
        displayName: 'Publish Security Analysis Logs'
        continueOnError: true
        condition: succeededOrFailed()

      - task: PostAnalysis@2
        displayName: 'Post Analysis'
        inputs:
          GdnBreakPolicyMinSev: Warning
          GdnBreakAllTools: true
        continueOnError: false
        condition: succeededOrFailed()

