name: "Validate Azure Bicep Action"
description: "Validate an Azure Bicep template"
inputs:
  bicep-path:
    description: Path to the Azure Bicep file.
    required: true
  output-path:
    description: Path to generated Azure ARM file.
    required: true
    default: ${{ runner.temp }}/azuredeploy.json
runs:
  using: composite
  steps:
    # Validate Azure Bicep changes.
    - name: Bicep Build
      uses: azure/bicep-build-action@v1.0.0
      with:
        bicepFilePath: ${{ inputs.bicep-path }}
        outputFilePath: ${{ inputs.output-path }}
