name: "Validate Terraform configuration"
description: "Validate Terraform configuration file"
inputs:
  terraform_version:
    description: The version of Terraform to be used.
    required: true
  working_directory:
    description: The directory in which to run the commands.
    required: true

runs:
  using: composite

  steps:
    # Validate Terraform changes.
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ inputs.terraform_version }}

    - uses: actions/cache@v3
      name: Cache plugin dir
      with:
        path: ${{ inputs.working_directory }}/.terraform
        key: ${GITHUB_SHA}

    - name: Setup TFLint
      uses: terraform-linters/setup-tflint@v2
      with:
        tflint_version: v0.41.0

    - name: Show version
      shell: bash
      run: tflint --version

    - name: Init TFLint
      shell: bash
      run: tflint --init

    - name: Run TFLint
      shell: bash
      run: tflint -f compact

    - name: Terraform Init
      id: init
      shell: bash
      run: terraform init
      working-directory: ${{ inputs.working_directory }}

    - name: Terraform Validate
      id: validate
      shell: bash
      run: terraform validate
      working-directory: ${{ inputs.working_directory }}
