name: "Build Azure Bicep Action"
description: "Build an Azure Bicep template"
inputs:
  azure-resource-group-name:
    description: The Azure resource group name.
    required: true
  azure-resource-group-location:
    description: The Azure region.
    required: true
  bicep-path:
    description: Path to the Azure Bicep file.
    required: true
  bicep-parameters:
    description: Parameters used in the Azure Bicep file.
    required: false
runs:
  using: composite
  steps:
    # Checkout code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Log into Azure
    - name: "Az CLI login"
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    # Ensure resource group is created
    - name: Create Resource Group
      uses: Azure/CLI@v1
      with:
        inlineScript: |
          #!/bin/bash
          az group create --name ${{ inputs.azure-resource-group-name }} --location ${{ inputs.azure-resource-group-location }}
          echo "Azure resource group created."

    # Validate Azure Bicep changes.
    - name: Preview Azure Bicep Changes
      uses: azure/deployment-what-if-action@v1.0.0
      with:
        subscription: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroup: ${{ inputs.azure-resource-group-name }}
        templateFile: ${{ inputs.bicep-path}}
        additionalParameters: ${{ inputs.bicep-parameters}}
