name: Azure Databricks Recipe CI

on:
  workflow_dispatch:
  push:
    paths:
      - src/az-databricks/**
      - .github/workflows/databricks-recipe-ci.yml
  pull_request:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  validate-bicep:
    runs-on: ubuntu-latest
    name: Validate Azure Bicep template
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/validate-bicep
        with:
          bicep-path: ./src/az-databricks/deploy/bicep/main.bicep
