name: Event Hub Recipe CI
on:
  workflow_dispatch:
  push:
    paths:
      - src/az-func-event-hub/**
      - src/common/app_code/eventhub-trigger/**
      - .github/workflows/event-hub-recipe-ci.yml
  pull_request:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  build-code:
    name: Build .NET Code
    uses: ./.github/workflows/dotnet-build.yml
    with:
      dotnet_version: "6.0.x"
      working_directory: "./src/common/app_code/eventhub-trigger/"
    secrets: inherit

  validate-bicep:
    runs-on: ubuntu-latest
    name: Validate Azure Bicep template
    environment: ${{ github.event.repository.name}}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/validate-bicep
        with:
          bicep-path: ./src/az-func-event-hub/deploy/bicep/main.bicep

  validate-terraform:
    runs-on: ubuntu-latest
    name: Validate Terraform configuration
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/validate-terraform
        with:
          terraform_version: "1.3.2"
          working_directory: ./src/az-func-event-hub/deploy/terraform/
