name: Event Hub Recipe CI
on:
  workflow_dispatch:
  push:
    paths:
      - src/az-func-event-hub/**
      - src/common/app_code/eventhub-trigger/**
      - .github/workflows/event-hub-recipe-ci.yml
  pull_request:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  build-code:
    uses: ./.github/workflows/dotnet-build.yml
    with:
      dotnet_version: "3.1.x"
      working_directory: "./src/common/app_code/eventhub-trigger/"
      env: ${{ github.event.repository.name}}-branch
    secrets: inherit

  validate-bicep:
    uses: ./.github/workflows/bicep-build.yml
    with:
      azure-resource-group-name: "rg-funcevhrcp-gh-bicep"
      azure-resource-group-location: "eastus"
      bicep-path: ./src/az-func-event-hub/deploy/bicep/main.bicep
    secrets: inherit

  validate-terraform:
    uses: ./.github/workflows/terraform-build.yml
    with:
      working_directory: ./src/az-func-event-hub/deploy/terraform/
      terraform_version: "1.3.2"
      terraform_variables: -var "resource_group_name=rg-funcevhrcp-gh-tf" -var "dns_zone_resource_group_name=rg-funcevhrcp-gh-tf" -var "newOrExistingDnsZones=new" -var "location=eastus" -var "tags={environment=\"Azure-Samples\"}"
    secrets: inherit
