name: Private Function HTTP Recipe CI

on:
  workflow_dispatch:
  push:
    paths:
      - src/az-func-http/**
      - .github/workflows/private-http-recipe-ci.yml
  pull_request:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  # TODO: VALIDATE PYTHON

  validate-bicep:
    runs-on: ubuntu-latest
    name: Validate Azure Bicep template
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/validate-bicep
        with:
          bicep-path: ./src/az-func-http/deploy/bicep/main.bicep

  validate-terraform:
    runs-on: ubuntu-latest
    name: Validate Terraform configuration
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/validate-terraform
        with:
          terraform_version: "1.3.2"
          working_directory: ./src/az-func-http/deploy/terraform/
