name: Private Function HTTP Recipe CI

on:
  workflow_dispatch:
  push:
    paths:
      - src/az-func-http/**
      - .github/workflows/private-http-recipe-ci.yml
    branches: 
      - main

permissions:
  id-token: write
  contents: read

env:
  AZURE_REGION: eastus

jobs:
  # TODO: VALIDATE PYTHON

  validate-bicep:
    runs-on: ubuntu-latest
    name: Validate Azure Bicep template
    environment: ${{ github.event.repository.name}}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/validate-bicep
        with:
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azure-resource-group-name: "rg-funchttprcpi-gh-bicep"
          azure-resource-group-location: ${{ env.AZURE_REGION }}
          bicep-path: ./src/az-func-http/deploy/bicep/main.bicep

  validate-terraform:
    runs-on: ubuntu-latest
    name: Validate Terraform configuration
    environment: ${{ github.event.repository.name}}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/validate-terraform
        env:
          RESOURCE_GROUP_NAME: rg-funchttprcpi-gh-tf
        with:
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          terraform_version: "1.3.2"
          terraform_variables: -var "resource_group_name=${{ env.RESOURCE_GROUP_NAME }}" -var "dns_zone_resource_group_name=${{ env.RESOURCE_GROUP_NAME }}" -var "newOrExistingDnsZones=new" -var "location=${{ env.AZURE_REGION }}" -var "tags={environment=\"Azure-Samples\"}"
          working_directory: ./src/az-func-http/deploy/terraform/
