name: Private Function HTTP Recipe CI

on:
  workflow_dispatch:
  push:
    paths:
      - src/az-func-http/**
      - .github/workflows/private-http-recipe-ci.yml
  pull_request:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  # TODO: VALIDATE PYTHON

  # validate-bicep:
  #   uses: ./.github/workflows/bicep-build.yml
  #   with:
  #     azure-resource-group-name: "rg-funchttprcpi-gh-bicep"
  #     azure-resource-group-location: "eastus"
  #     bicep-path: ./src/az-func-http/deploy/bicep/main.bicep
  #   secrets: inherit

  # validate-terraform:
  #   uses: ./.github/workflows/terraform-build.yml
  #   with:
  #     working_directory: ./src/az-func-http/deploy/terraform/
  #     terraform_version: "1.3.2"
  #     terraform_variables: -var "resource_group_name=rg-funchttprcpi-gh-tf" -var "dns_zone_resource_group_name=rg-funchttprcpi-gh-tf" -var "newOrExistingDnsZones=new" -var "location=eastus" -var "tags={environment=\"Azure-Samples\"}"
  #   secrets: inherit

  validate-bicep:
    runs-on: ubuntu-latest
    name: Validate Azure Bicep template
    environment: ${{ github.event.repository.name}}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/validate-bicep
        with:
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azure-resource-group-name: "rg-funchttprcpi-gh-bicep"
          azure-resource-group-location: "eastus"
          bicep-path: ./src/az-func-http/deploy/bicep/main.bicep

  validate-terraform:
    runs-on: ubuntu-latest
    name: Validate Terraform configuration
    environment: ${{ github.event.repository.name}}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/validate-terraform
        with:
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          terraform_version: "1.3.2"
          terraform_variables: -var "resource_group_name=rg-funchttprcpi-gh-tf" -var "dns_zone_resource_group_name=rg-funchttprcpi-gh-tf" -var "newOrExistingDnsZones=new" -var "location=eastus" -var "tags={environment=\"Azure-Samples\"}"
          working_directory: ./src/az-func-http/deploy/terraform/
