name: Microsoft Purview Recipe CI

on:
  workflow_dispatch:
  push:
    paths:
      - src/az-purview/deploy/**
      - .github/workflows/purview-recipe-ci.yml
  pull_request:
    branches: [main]

permissions:
  id-token: write
  contents: read

env:
  AZURE_REGION: eastus

jobs:
  validate-bicep:
    runs-on: ubuntu-latest
    name: Validate Bicep
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/validate-bicep
        with:
          bicep-path: ./src/az-purview/deploy/bicep/main.bicep
  
  validate-terraform:
    runs-on: ubuntu-latest
    name: Validate Terraform
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/validate-terraform
        with:
          terraform_version: "1.3.2"
          working_directory: ./src/az-purview/deploy/terraform/
