name: Terraform Lint

on:
  workflow_call:
    inputs:
      working_directory:
        required: true
        type: string

jobs:
  lint-terraform:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      - uses: actions/cache@v3
        name: Cache plugin dir
        with:
          path: ${{ inputs.working_directory }}
          key: ${{ runner.os }}-tflint-${{ hashFiles('.tflint.hcl') }}

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v2
        with:
          tflint_version: v0.41.0

      - name: Show version
        run: tflint --version

      - name: Init TFLint
        run: tflint --init

      - name: Run TFLint
        run: tflint -f compact
