name: Web App Private HTTP Recipe CI
on:
  workflow_dispatch:
  push:
    paths:
      - src/common/app_code/WeatherForecastAPI/**
      - src/az-webapp-http/**
      - .github/workflows/webapp-private-http-recipe-ci.yml
  pull_request:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  build-code:
    uses: ./.github/workflows/dotnet-build.yml
    with:
      dotnet_version: "3.1.x"
      working_directory: "./src/common/app_code/WeatherForecastAPI/"
    secrets: inherit

  validate-bicep:
    uses: ./.github/workflows/bicep-build.yml
    with:
      azure-resource-group-name: "rg-webhttprcpi-gh-bicep"
      azure-resource-group-location: "eastus"
      bicep-path: ./src/az-webapp-http/deploy/bicep/main.bicep
    secrets: inherit

  validate-terraform:
    uses: ./.github/workflows/terraform-build.yml
    with:
      working_directory: ./src/az-webapp-http/deploy/terraform/
      terraform_version: "1.3.2"
      terraform_variables: -var "resource_group_name=rg-webhttprcpi-gh-tf" -var "dns_zone_resource_group_name=rg-webhttprcpi-gh-tf" -var "newOrExistingDnsZones=new" -var "location=eastus" -var "tags={environment=\"Azure-Samples\"}"
    secrets: inherit
