name: Web App Private HTTP Recipe CI
on:
  workflow_dispatch:
  push:
    paths:
      - src/common/app_code/WeatherForecastAPI/**
      - src/az-webapp-http/**
      - .github/workflows/webapp-private-http-recipe-ci.yml
  pull_request:
    branches: [main]

permissions:
  id-token: write
  contents: read

env:
  AZURE_REGION: eastus

jobs:
  build-code:
    name: Build .NET Code
    uses: ./.github/workflows/dotnet-build.yml
    with:
      dotnet_version: "6.0.x"
      working_directory: "./src/common/app_code/WeatherForecastAPI/"
    secrets: inherit

  validate-bicep:
    runs-on: ubuntu-latest
    name: Validate Azure Bicep template
    environment: ${{ github.event.repository.name}}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/validate-bicep
        with:
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azure-resource-group-name: "rg-webhttprcpi-gh-bicep"
          azure-resource-group-location: ${{ env.AZURE_REGION }}
          bicep-path: ./src/az-webapp-http/deploy/bicep/main.bicep

  validate-terraform:
    runs-on: ubuntu-latest
    name: Validate Terraform configuration
    environment: ${{ github.event.repository.name}}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/validate-terraform
        env:
          RESOURCE_GROUP_NAME: rg-webhttprcpi-gh-tf
        with:
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          terraform_version: "1.3.2"
          terraform_variables: -var "resource_group_name=${{ env.RESOURCE_GROUP_NAME }}" -var "dns_zone_resource_group_name=${{ env.RESOURCE_GROUP_NAME }}" -var "newOrExistingDnsZones=new" -var "location=${{ env.AZURE_REGION }}" -var "tags={environment=\"Azure-Samples\"}"
          working_directory: ./src/az-webapp-http/deploy/terraform/
